# npx netlify deploy --build --prod --skip-functions-cache
[build]
  base = "./"
  command = "npm run tsc && npm run test && npm run build"
  publish = "./dist/"
[functions.api]
  external_node_modules = [
    "jsdom"
  ]
[[redirects]]
  force = true
  from = "/api/*"
  status = 200
  to = "/.netlify/functions/api/:splat"
[[redirects]]
  from = "/*"
  status = 200
  to = "/index.html"