[build]
  base = "./"
  command = "npm run typecheck && npm run build"
  publish = "./dist/"
[[redirects]]
  force = true
  from = "/api/*"
  status = 200
  to = "/.netlify/functions/api/:splat"
[[redirects]]
  from = "/*"
  status = 200
  to = "/index.html"